-- TAJ ERP — Settings table only
-- Run in Supabase → SQL Editor

create table if not exists app_settings (
  id bigint generated by default as identity primary key,
  company_name text default 'TAJ ERP',
  company_phone text,
  company_address text,
  working_days int default 26,
  shift_start text default '08:00',
  shift_end text default '17:00',
  currency text default 'INR',
  updated_at timestamptz default now()
);

alter table app_settings enable row level security;

drop policy if exists "app_settings_all" on app_settings;

create policy "app_settings_all"
on app_settings
for all
using (true)
with check (true);

insert into app_settings (
  company_name,
  working_days,
  shift_start,
  shift_end,
  currency
)
select 'TAJ ERP', 26, '08:00', '17:00', 'INR'
where not exists (select 1 from app_settings);
