-- ============================================================
-- TAJ ERP — Full Supabase Database Setup
-- Paste this entire file into: Supabase → SQL Editor → Run
-- ============================================================

-- ------------------------------------------------------------
-- 1. EMPLOYEES
-- ------------------------------------------------------------
create table if not exists employees (
  id bigint generated by default as identity primary key,
  employee_id text unique not null,
  full_name text,
  phone text,
  email text,
  address text,
  department text,
  password text not null,
  role text default 'worker',
  salary numeric default 0,
  emergency_contact text,
  requested_role text,
  selfie_url text,
  profile_photo text,
  registration_status text default 'approved',
  approval_status text default 'approved',
  rejected_reason text,
  status text default 'active',
  created_at timestamptz default now()
);

-- ------------------------------------------------------------
-- 2. EMPLOYEE PERMISSIONS (sidebar access control)
-- ------------------------------------------------------------
create table if not exists employee_permissions (
  id bigint generated by default as identity primary key,
  employee_id text unique not null,
  dashboard boolean default true,
  employees boolean default false,
  attendance boolean default true,
  salary boolean default false,
  stock boolean default false,
  orders boolean default false,
  reports boolean default false,
  settings boolean default false,
  calls boolean default false
);

-- ------------------------------------------------------------
-- 3. ATTENDANCE
-- ------------------------------------------------------------
create table if not exists attendance (
  id bigint generated by default as identity primary key,
  employee_id text not null,
  check_in timestamptz,
  check_out timestamptz,
  status text default 'present',
  selfie_url text,
  latitude text,
  longitude text,
  created_at timestamptz default now()
);

-- ------------------------------------------------------------
-- 4. TASKS
-- ------------------------------------------------------------
create table if not exists tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  assigned_to text not null,
  priority text default 'medium',
  deadline date,
  status text default 'pending',
  created_at timestamptz default now()
);

-- ------------------------------------------------------------
-- 5. STOCK (raw materials)
-- ------------------------------------------------------------
create table if not exists stock (
  id bigint generated by default as identity primary key,
  item_name text not null,
  category text,
  quantity numeric default 0,
  unit text default 'KG',
  supplier text,
  minimum_stock numeric default 10,
  rating text,
  quality text,
  water_required text,
  salt_required text,
  mixing_notes text,
  feedback text,
  tested_by text,
  status text,
  created_at timestamptz default now()
);

-- ------------------------------------------------------------
-- 6. SALARY PAYMENTS
-- ------------------------------------------------------------
create table if not exists salary_payments (
  id bigint generated by default as identity primary key,
  employee_id text not null,
  month int not null,
  year int not null,
  base_salary numeric default 0,
  present_days int default 0,
  deductions numeric default 0,
  bonus numeric default 0,
  net_salary numeric default 0,
  status text default 'paid',
  notes text,
  created_at timestamptz default now()
);

-- ------------------------------------------------------------
-- 7. ORDERS (factory dispatch / delivery orders)
-- ------------------------------------------------------------
create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_number text,
  customer_name text not null,
  customer_phone text,
  product_name text not null,
  quantity numeric not null default 0,
  unit text default 'KG',
  amount numeric default 0,
  delivery_address text,
  delivery_date date,
  assigned_to text,
  status text default 'pending',
  notes text,
  created_by text,
  created_at timestamptz default now()
);

-- ------------------------------------------------------------
-- 8. APP SETTINGS
-- ------------------------------------------------------------
create table if not exists app_settings (
  id bigint generated by default as identity primary key,
  company_name text default 'TAJ ERP',
  company_phone text,
  company_address text,
  working_days int default 26,
  shift_start text default '08:00',
  shift_end text default '17:00',
  currency text default 'INR',
  updated_at timestamptz default now()
);

-- ------------------------------------------------------------
-- 9. CALLS (internal factory staff communication)
-- ------------------------------------------------------------
create table if not exists calls (
  id bigint generated by default as identity primary key,
  called_by text not null,
  called_to text not null,
  topic text default 'general',
  call_type text default 'phone',
  purpose text,
  status text default 'open',
  follow_up_date date,
  notes text,
  customer_name text,
  customer_phone text,
  created_at timestamptz default now()
);

-- ============================================================
-- ROW LEVEL SECURITY (open for development)
-- Tighten these policies before going to production!
-- ============================================================

alter table employees enable row level security;
alter table employee_permissions enable row level security;
alter table attendance enable row level security;
alter table tasks enable row level security;
alter table stock enable row level security;
alter table salary_payments enable row level security;
alter table orders enable row level security;
alter table app_settings enable row level security;
alter table calls enable row level security;

create policy "employees_all" on employees for all using (true) with check (true);
create policy "employee_permissions_all" on employee_permissions for all using (true) with check (true);
create policy "attendance_all" on attendance for all using (true) with check (true);
create policy "tasks_all" on tasks for all using (true) with check (true);
create policy "stock_all" on stock for all using (true) with check (true);
create policy "salary_payments_all" on salary_payments for all using (true) with check (true);
create policy "orders_all" on orders for all using (true) with check (true);
create policy "app_settings_all" on app_settings for all using (true) with check (true);
create policy "calls_all" on calls for all using (true) with check (true);

-- ============================================================
-- STORAGE BUCKET (employee registration selfies)
-- Supabase → Storage → create bucket if this fails
-- ============================================================

insert into storage.buckets (id, name, public)
values ('employee-selfies', 'employee-selfies', true)
on conflict (id) do nothing;

create policy "selfies_public_read"
on storage.objects for select
using (bucket_id = 'employee-selfies');

create policy "selfies_upload"
on storage.objects for insert
with check (bucket_id = 'employee-selfies');

create policy "selfies_update"
on storage.objects for update
using (bucket_id = 'employee-selfies');

-- ============================================================
-- DEFAULT SETTINGS ROW
-- ============================================================

insert into app_settings (
  company_name,
  company_phone,
  company_address,
  working_days,
  shift_start,
  shift_end,
  currency
) values (
  'TAJ ERP',
  '',
  '',
  26,
  '08:00',
  '17:00',
  'INR'
);

-- ============================================================
-- FIRST ADMIN USER (login: EMP001 / password: admin123)
-- Change the password after first login!
-- ============================================================

insert into employees (
  employee_id,
  full_name,
  phone,
  email,
  department,
  password,
  role,
  salary,
  approval_status,
  registration_status,
  status
) values (
  'EMP001',
  'Factory Admin',
  '9999999999',
  'admin@tajerp.com',
  'Management',
  'admin123',
  'admin',
  50000,
  'approved',
  'approved',
  'active'
);

insert into employee_permissions (
  employee_id,
  dashboard,
  employees,
  attendance,
  salary,
  stock,
  orders,
  reports,
  settings,
  calls
) values (
  'EMP001',
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true
);

-- ============================================================
-- DONE! Login with:
--   Employee ID: EMP001
--   Password:    admin123
-- ============================================================
