-- ============================================================
-- TAJ ERP — Secure RLS Policies (corrected)
-- Run in Supabase → SQL Editor
--
-- Fix notes:
--   - All function bodies use $fn$ ... $fn$ (not $$)
--   - Avoids '$2%' inside dollar-quotes (Postgres treats $2 as a quote tag)
-- ============================================================

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- ------------------------------------------------------------
-- Password secrets (never exposed via Data API)
-- ------------------------------------------------------------
create table if not exists employee_secrets (
  employee_id text primary key,
  password_hash text not null,
  updated_at timestamptz default now()
);

alter table employee_secrets enable row level security;

drop policy if exists "employee_secrets_deny" on employee_secrets;
create policy "employee_secrets_deny" on employee_secrets
for all using (false) with check (false);

alter table employees alter column password drop not null;

insert into employee_secrets (employee_id, password_hash)
select employee_id, password
from employees
where coalesce(password, '') <> ''
  and password not in ('', 'REDACTED')
on conflict (employee_id) do update
set password_hash = excluded.password_hash,
    updated_at = now();

update employees
set password = 'REDACTED'
where coalesce(password, '') <> ''
  and password <> 'REDACTED';

create or replace function public.sync_employee_secret()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
begin
  if tg_op = 'INSERT' or tg_op = 'UPDATE' then
    if new.password is not null
      and new.password <> ''
      and new.password <> 'REDACTED'
    then
      insert into employee_secrets (employee_id, password_hash, updated_at)
      values (new.employee_id, new.password, now())
      on conflict (employee_id) do update
      set password_hash = excluded.password_hash,
          updated_at = now();

      new.password := 'REDACTED';
    end if;
  end if;

  return new;
end;
$fn$;

drop trigger if exists trg_sync_employee_secret on employees;
create trigger trg_sync_employee_secret
before insert or update of password on employees
for each row
execute function public.sync_employee_secret();

-- ------------------------------------------------------------
-- Sessions
-- ------------------------------------------------------------
create table if not exists erp_sessions (
  id bigint generated by default as identity primary key,
  employee_id text not null references employees(employee_id) on delete cascade,
  token text unique not null,
  expires_at timestamptz not null,
  created_at timestamptz default now()
);

create index if not exists erp_sessions_token_idx on erp_sessions (token);
create index if not exists erp_sessions_employee_idx on erp_sessions (employee_id);

alter table erp_sessions enable row level security;

-- ------------------------------------------------------------
-- Helpers
-- ------------------------------------------------------------
create or replace function public.request_erp_token()
returns text
language plpgsql
stable
as $fn$
declare
  headers json;
  token text;
begin
  begin
    headers := current_setting('request.headers', true)::json;
  exception when others then
    return null;
  end;

  if headers is null then
    return null;
  end if;

  token := coalesce(
    headers->>'x-erp-token',
    headers->>'X-Erp-Token'
  );

  return nullif(token, '');
end;
$fn$;

create or replace function public.current_employee_id()
returns text
language sql
stable
security definer
set search_path = public
as $fn$
  select s.employee_id
  from erp_sessions s
  where s.token = public.request_erp_token()
    and s.expires_at > now()
  limit 1;
$fn$;

create or replace function public.current_employee_role()
returns text
language sql
stable
security definer
set search_path = public
as $fn$
  select lower(trim(e.role))
  from employees e
  where e.employee_id = public.current_employee_id()
  limit 1;
$fn$;

create or replace function public.is_session_valid()
returns boolean
language sql
stable
security definer
set search_path = public
as $fn$
  select public.current_employee_id() is not null;
$fn$;

create or replace function public.is_non_worker()
returns boolean
language sql
stable
security definer
set search_path = public
as $fn$
  select coalesce(public.current_employee_role(), 'worker') <> 'worker';
$fn$;

create or replace function public.is_bcrypt_hash(p_value text)
returns boolean
language sql
immutable
as $fn$
  select p_value ~ '^\$2[aby]\$';
$fn$;

create or replace function public.has_app_permission(p_module text)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $fn$
declare
  eid text := public.current_employee_id();
  r text;
  allowed boolean := false;
begin
  if eid is null then
    return false;
  end if;

  if p_module not in (
    'dashboard', 'employees', 'attendance', 'tasks', 'salary',
    'stock', 'orders', 'reports', 'settings', 'calls', 'wallet'
  ) then
    return false;
  end if;

  select lower(trim(role)) into r
  from employees
  where employee_id = eid;

  if r = 'admin' then
    return true;
  end if;

  if p_module = 'wallet' and r in ('manager', 'accountant', 'shopkeeper') then
    return true;
  end if;

  if p_module = 'tasks' then
    select coalesce(p.tasks, p.attendance, false) into allowed
    from employee_permissions p
    where p.employee_id = eid;
    return coalesce(allowed, false);
  end if;

  execute format(
    'select coalesce(%I, false) from employee_permissions where employee_id = $1',
    p_module
  ) into allowed using eid;

  return coalesce(allowed, false);
end;
$fn$;

-- ------------------------------------------------------------
-- Auth RPCs
-- ------------------------------------------------------------
create or replace function public.login_employee(
  p_employee_id text,
  p_password text
)
returns json
language plpgsql
security definer
set search_path = public, extensions
as $fn$
declare
  emp employees%rowtype;
  stored_hash text;
  password_ok boolean := false;
  new_token text;
  new_hash text;
begin
  if p_employee_id is null or p_password is null then
    raise exception 'Employee ID and password are required';
  end if;

  select * into emp
  from employees
  where employee_id = p_employee_id
  limit 1;

  if not found then
    raise exception 'Invalid Employee ID or Password';
  end if;

  select password_hash into stored_hash
  from employee_secrets
  where employee_id = p_employee_id;

  if stored_hash is null
    and emp.password is not null
    and emp.password <> 'REDACTED'
  then
    stored_hash := emp.password;
  end if;

  if stored_hash is null then
    raise exception 'Invalid Employee ID or Password';
  end if;

  if public.is_bcrypt_hash(stored_hash) then
    password_ok := (stored_hash = crypt(p_password, stored_hash));
  else
    password_ok := (stored_hash = p_password);
    if password_ok then
      new_hash := crypt(p_password, gen_salt('bf', 10));
      insert into employee_secrets (employee_id, password_hash, updated_at)
      values (emp.employee_id, new_hash, now())
      on conflict (employee_id) do update
      set password_hash = excluded.password_hash,
          updated_at = now();
    end if;
  end if;

  if not password_ok then
    raise exception 'Invalid Employee ID or Password';
  end if;

  if coalesce(emp.approval_status, '') <> 'approved' then
    return json_build_object(
      'employee_id', emp.employee_id,
      'approval_status', emp.approval_status,
      'token', null
    );
  end if;

  new_token := encode(gen_random_bytes(32), 'hex');

  delete from erp_sessions
  where employee_id = emp.employee_id
     or expires_at <= now();

  insert into erp_sessions (employee_id, token, expires_at)
  values (emp.employee_id, new_token, now() + interval '14 days');

  return json_build_object(
    'employee_id', emp.employee_id,
    'approval_status', emp.approval_status,
    'token', new_token,
    'role', emp.role,
    'full_name', emp.full_name
  );
end;
$fn$;

create or replace function public.logout_employee()
returns boolean
language plpgsql
security definer
set search_path = public
as $fn$
begin
  delete from erp_sessions
  where token = public.request_erp_token();
  return true;
end;
$fn$;

create or replace function public.register_employee(
  p_full_name text,
  p_phone text,
  p_email text,
  p_address text,
  p_password text,
  p_requested_role text,
  p_selfie_url text default ''
)
returns json
language plpgsql
security definer
set search_path = public, extensions
as $fn$
declare
  new_id text;
  hashed text;
begin
  if p_full_name is null or p_phone is null or p_password is null then
    raise exception 'Please fill all required fields';
  end if;

  new_id := 'PENDING-' || floor(extract(epoch from now()) * 1000)::bigint::text;
  hashed := crypt(p_password, gen_salt('bf', 10));

  insert into employees (
    employee_id,
    full_name,
    phone,
    email,
    address,
    password,
    requested_role,
    selfie_url,
    registration_status,
    approval_status,
    status
  ) values (
    new_id,
    p_full_name,
    p_phone,
    p_email,
    p_address,
    hashed,
    coalesce(nullif(p_requested_role, ''), 'worker'),
    coalesce(p_selfie_url, ''),
    'pending',
    'pending',
    'inactive'
  );

  return json_build_object(
    'employee_id', new_id,
    'status', 'pending'
  );
end;
$fn$;

grant execute on function public.login_employee(text, text) to anon, authenticated;
grant execute on function public.logout_employee() to anon, authenticated;
grant execute on function public.register_employee(text, text, text, text, text, text, text) to anon, authenticated;
grant execute on function public.current_employee_id() to anon, authenticated;
grant execute on function public.has_app_permission(text) to anon, authenticated;
grant execute on function public.is_session_valid() to anon, authenticated;

-- ------------------------------------------------------------
-- Drop old policies
-- ------------------------------------------------------------
drop policy if exists "employees_all" on employees;
drop policy if exists "employee_permissions_all" on employee_permissions;
drop policy if exists "attendance_all" on attendance;
drop policy if exists "tasks_all" on tasks;
drop policy if exists "stock_all" on stock;
drop policy if exists "salary_payments_all" on salary_payments;
drop policy if exists "orders_all" on orders;
drop policy if exists "app_settings_all" on app_settings;
drop policy if exists "calls_all" on calls;
drop policy if exists "wallets_all" on wallets;
drop policy if exists "shopkeepers_all" on shopkeepers;
drop policy if exists "wallet_transactions_all" on wallet_transactions;

drop policy if exists "employees_select" on employees;
drop policy if exists "employees_insert" on employees;
drop policy if exists "employees_update" on employees;
drop policy if exists "employees_delete" on employees;
drop policy if exists "permissions_select" on employee_permissions;
drop policy if exists "permissions_write" on employee_permissions;
drop policy if exists "attendance_select" on attendance;
drop policy if exists "attendance_insert" on attendance;
drop policy if exists "attendance_update" on attendance;
drop policy if exists "attendance_delete" on attendance;
drop policy if exists "tasks_select" on tasks;
drop policy if exists "tasks_insert" on tasks;
drop policy if exists "tasks_update" on tasks;
drop policy if exists "tasks_delete" on tasks;
drop policy if exists "stock_all_secure" on stock;
drop policy if exists "stock_reports_read" on stock;
drop policy if exists "salary_select" on salary_payments;
drop policy if exists "salary_write" on salary_payments;
drop policy if exists "orders_all_secure" on orders;
drop policy if exists "orders_reports_read" on orders;
drop policy if exists "settings_select" on app_settings;
drop policy if exists "settings_write" on app_settings;
drop policy if exists "calls_select" on calls;
drop policy if exists "calls_insert" on calls;
drop policy if exists "calls_update" on calls;
drop policy if exists "calls_delete" on calls;
drop policy if exists "calls_all_secure" on calls;
drop policy if exists "wallets_all_secure" on wallets;
drop policy if exists "shopkeepers_all_secure" on shopkeepers;
drop policy if exists "wallet_tx_all_secure" on wallet_transactions;
drop policy if exists "erp_sessions_deny" on erp_sessions;
drop policy if exists "tasks_reports_read" on tasks;

-- ------------------------------------------------------------
-- Enable RLS
-- ------------------------------------------------------------
alter table employees enable row level security;
alter table employee_permissions enable row level security;
alter table attendance enable row level security;
alter table tasks enable row level security;
alter table stock enable row level security;
alter table salary_payments enable row level security;
alter table orders enable row level security;
alter table app_settings enable row level security;
alter table calls enable row level security;
alter table wallets enable row level security;
alter table shopkeepers enable row level security;
alter table wallet_transactions enable row level security;
alter table erp_sessions enable row level security;
alter table employee_secrets enable row level security;

revoke all on table employee_secrets from anon, authenticated;

-- ------------------------------------------------------------
-- employees
-- ------------------------------------------------------------
create policy "employees_select" on employees
for select using (public.is_session_valid());

create policy "employees_insert" on employees
for insert with check (public.has_app_permission('employees'));

create policy "employees_update" on employees
for update using (public.has_app_permission('employees'));

create policy "employees_delete" on employees
for delete using (public.has_app_permission('employees'));

-- ------------------------------------------------------------
-- employee_permissions
-- ------------------------------------------------------------
create policy "permissions_select" on employee_permissions
for select using (
  employee_id = public.current_employee_id()
  or public.has_app_permission('employees')
);

create policy "permissions_write" on employee_permissions
for all using (public.has_app_permission('employees'))
with check (public.has_app_permission('employees'));

-- ------------------------------------------------------------
-- attendance
-- ------------------------------------------------------------
create policy "attendance_select" on attendance
for select using (
  employee_id = public.current_employee_id()
  or public.is_non_worker()
);

create policy "attendance_insert" on attendance
for insert with check (
  employee_id = public.current_employee_id()
  or public.has_app_permission('attendance')
);

create policy "attendance_update" on attendance
for update using (
  employee_id = public.current_employee_id()
  or public.has_app_permission('attendance')
  or public.is_non_worker()
);

create policy "attendance_delete" on attendance
for delete using (
  public.has_app_permission('attendance')
  or public.is_non_worker()
);

-- ------------------------------------------------------------
-- tasks
-- ------------------------------------------------------------
create policy "tasks_select" on tasks
for select using (
  assigned_to = public.current_employee_id()
  or public.has_app_permission('tasks')
  or public.is_non_worker()
);

create policy "tasks_insert" on tasks
for insert with check (
  public.has_app_permission('tasks')
  or public.is_non_worker()
);

create policy "tasks_update" on tasks
for update using (
  assigned_to = public.current_employee_id()
  or public.has_app_permission('tasks')
  or public.is_non_worker()
);

create policy "tasks_delete" on tasks
for delete using (
  public.has_app_permission('tasks')
  or public.is_non_worker()
);

create policy "tasks_reports_read" on tasks
for select using (public.has_app_permission('reports'));

-- ------------------------------------------------------------
-- stock / orders
-- ------------------------------------------------------------
create policy "stock_all_secure" on stock
for all using (public.has_app_permission('stock'))
with check (public.has_app_permission('stock'));

create policy "stock_reports_read" on stock
for select using (public.has_app_permission('reports'));

create policy "orders_all_secure" on orders
for all using (
  public.has_app_permission('orders')
  or assigned_to = public.current_employee_id()
)
with check (public.has_app_permission('orders'));

create policy "orders_reports_read" on orders
for select using (public.has_app_permission('reports'));

-- ------------------------------------------------------------
-- calls
-- ------------------------------------------------------------
create policy "calls_select" on calls
for select using (
  public.has_app_permission('calls')
  or called_by = public.current_employee_id()
  or called_to = public.current_employee_id()
);

create policy "calls_insert" on calls
for insert with check (
  public.has_app_permission('calls')
  and called_by = public.current_employee_id()
);

create policy "calls_update" on calls
for update using (
  public.has_app_permission('calls')
  or called_by = public.current_employee_id()
  or called_to = public.current_employee_id()
);

create policy "calls_delete" on calls
for delete using (public.has_app_permission('calls'));

-- ------------------------------------------------------------
-- salary_payments
-- ------------------------------------------------------------
create policy "salary_select" on salary_payments
for select using (
  employee_id = public.current_employee_id()
  or public.has_app_permission('salary')
);

create policy "salary_write" on salary_payments
for all using (public.has_app_permission('salary'))
with check (public.has_app_permission('salary'));

-- ------------------------------------------------------------
-- app_settings
-- ------------------------------------------------------------
create policy "settings_select" on app_settings
for select using (public.is_session_valid());

create policy "settings_write" on app_settings
for all using (public.has_app_permission('settings'))
with check (public.has_app_permission('settings'));

-- ------------------------------------------------------------
-- wallet tables
-- ------------------------------------------------------------
create policy "wallets_all_secure" on wallets
for all using (
  public.has_app_permission('wallet')
  or employee_id = public.current_employee_id()
)
with check (
  public.has_app_permission('wallet')
  or employee_id = public.current_employee_id()
);

create policy "shopkeepers_all_secure" on shopkeepers
for all using (public.has_app_permission('wallet'))
with check (public.has_app_permission('wallet'));

create policy "wallet_tx_all_secure" on wallet_transactions
for all using (
  public.has_app_permission('wallet')
  or from_employee_id = public.current_employee_id()
  or created_by = public.current_employee_id()
)
with check (
  public.has_app_permission('wallet')
  or from_employee_id = public.current_employee_id()
  or created_by = public.current_employee_id()
);

create policy "erp_sessions_deny" on erp_sessions
for all using (false)
with check (false);

-- ------------------------------------------------------------
-- Grants (RLS still applies)
-- ------------------------------------------------------------
grant select, insert, update, delete on table employees to anon, authenticated;
grant select, insert, update, delete on table employee_permissions to anon, authenticated;
grant select, insert, update, delete on table attendance to anon, authenticated;
grant select, insert, update, delete on table tasks to anon, authenticated;
grant select, insert, update, delete on table stock to anon, authenticated;
grant select, insert, update, delete on table salary_payments to anon, authenticated;
grant select, insert, update, delete on table orders to anon, authenticated;
grant select, insert, update, delete on table app_settings to anon, authenticated;
grant select, insert, update, delete on table calls to anon, authenticated;
grant select, insert, update, delete on table wallets to anon, authenticated;
grant select, insert, update, delete on table shopkeepers to anon, authenticated;
grant select, insert, update, delete on table wallet_transactions to anon, authenticated;

grant usage, select on all sequences in schema public to anon, authenticated;

-- ============================================================
-- DONE
-- Log out, clear site data once, then log in again.
-- ============================================================
