-- ============================================================
-- TAJ ERP — Wallet / UPI Points System
-- Run in Supabase → SQL Editor
-- ============================================================

-- Add wallet permission column (if employees table already exists)
alter table employee_permissions
add column if not exists wallet boolean default false;

-- Employee wallets (points balance)
create table if not exists wallets (
  id bigint generated by default as identity primary key,
  employee_id text unique not null,
  balance numeric default 0,
  updated_at timestamptz default now()
);

-- Shopkeepers with unique QR codes
create table if not exists shopkeepers (
  id bigint generated by default as identity primary key,
  shopkeeper_code text unique not null,
  shop_name text not null,
  owner_name text,
  phone text,
  employee_id text unique,
  qr_token text unique not null,
  balance numeric default 0,
  total_received numeric default 0,
  total_settled numeric default 0,
  status text default 'active',
  created_at timestamptz default now()
);

-- All wallet transactions
create table if not exists wallet_transactions (
  id bigint generated by default as identity primary key,
  transaction_type text not null,
  from_employee_id text,
  to_shopkeeper_id text,
  amount numeric not null,
  employee_balance_after numeric,
  shopkeeper_balance_after numeric,
  notes text,
  created_by text,
  created_at timestamptz default now()
);

-- Security
alter table wallets enable row level security;
alter table shopkeepers enable row level security;
alter table wallet_transactions enable row level security;

drop policy if exists "wallets_all" on wallets;
drop policy if exists "shopkeepers_all" on shopkeepers;
drop policy if exists "wallet_transactions_all" on wallet_transactions;

create policy "wallets_all" on wallets for all using (true) with check (true);
create policy "shopkeepers_all" on shopkeepers for all using (true) with check (true);
create policy "wallet_transactions_all" on wallet_transactions for all using (true) with check (true);

-- Enable wallet for admin
update employee_permissions
set wallet = true
where employee_id = 'EMP001';
